# Generated by Django 3.2.7 on 2021-09-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='codePostal',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='client',
            name='localite',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
