# Generated by Django 3.2.7 on 2021-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210915_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientActif',
            field=models.BooleanField(default=True),
        ),
    ]
