# Generated by Django 3.2.7 on 2021-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_clientactif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mail',
        ),
        migrations.AlterField(
            model_name='client',
            name='codePostal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numerosMobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
