# Generated by Django 3.2.7 on 2021-09-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('stockMin', models.IntegerField()),
                ('stockMax', models.IntegerField()),
                ('stockDisponible', models.IntegerField()),
                ('poid', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetique',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.produit')),
                ('ingredient', models.CharField(max_length=100)),
                ('gamme', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=50)),
            ],
            bases=('shop.produit',),
        ),
        migrations.CreateModel(
            name='ProduitInterieur',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.produit')),
                ('type', models.CharField(max_length=20)),
            ],
            bases=('shop.produit',),
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.produit')),
                ('sexe', models.CharField(max_length=20)),
                ('typeTissu', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
            ],
            bases=('shop.produit',),
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('reduction', models.IntegerField()),
                ('date', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
            ],
        ),
    ]
