# Generated by Django 3.2.7 on 2021-09-20 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_atelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
