# Generated by Django 3.2.7 on 2021-09-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_favoris'),
        ('shop', '0004_photo_produitid'),
    ]

    operations = [
    ]
