# Generated by Django 3.2.7 on 2021-09-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_0003_produit_favoris_0004_photo_produitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='atelierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.atelier'),
        ),
    ]
