# Generated by Django 3.2.5 on 2021-09-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_photo_atelierid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='atelierId',
        ),
    ]
