# Generated by Django 3.2.7 on 2021-09-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_photo_atelierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='atelierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.atelier'),
        ),
    ]
