# Generated by Django 3.2.7 on 2021-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_photo_atelierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='produitActif',
            field=models.BooleanField(default=True),
        ),
    ]
