# Generated by Django 3.2.7 on 2021-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_produit_produitactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='AtelierActif',
            field=models.BooleanField(default=True),
        ),
    ]
