# Generated by Django 3.2.7 on 2021-09-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_clientactif'),
        ('shop', '0010_atelier_atelieractif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comNumero', models.IntegerField()),
                ('comTotal', models.DecimalField(decimal_places=3, max_digits=5)),
                ('comDatePaiement', models.DateField()),
                ('comPoidsFinal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('envoye', models.BooleanField(default=True)),
                ('enAttente', models.BooleanField(default=False)),
                ('clientId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
