# Generated by Django 3.2.7 on 2021-09-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_ligneatelier_lignecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneAtelierCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrPersonne', models.IntegerField()),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.atelier')),
            ],
        ),
        migrations.CreateModel(
            name='LigneProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='commandeId',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='produitId',
        ),
        migrations.AddField(
            model_name='commande',
            name='atelier',
            field=models.ManyToManyField(to='shop.Atelier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='shop.Produit'),
        ),
        migrations.DeleteModel(
            name='LigneAtelier',
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
        migrations.AddField(
            model_name='ligneproduitcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commande'),
        ),
        migrations.AddField(
            model_name='ligneproduitcommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit'),
        ),
        migrations.AddField(
            model_name='ligneateliercommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commande'),
        ),
        migrations.AlterUniqueTogether(
            name='ligneproduitcommande',
            unique_together={('produit', 'commande')},
        ),
        migrations.AlterUniqueTogether(
            name='ligneateliercommande',
            unique_together={('atelier', 'commande')},
        ),
    ]
