# Generated by Django 3.2.7 on 2021-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210930_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='atelier',
            field=models.ManyToManyField(blank=True, to='shop.Atelier'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(blank=True, to='shop.Produit'),
        ),
    ]
