# Generated by Django 3.2.7 on 2021-10-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210930_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligneateliercommande',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ligneateliercommande',
            name='atelier',
        ),
        migrations.RemoveField(
            model_name='ligneateliercommande',
            name='commande',
        ),
        migrations.AlterUniqueTogether(
            name='ligneproduitcommande',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ligneproduitcommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='ligneproduitcommande',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='LigneAtelierCommande',
        ),
        migrations.DeleteModel(
            name='LigneProduitCommande',
        ),
    ]
