# Generated by Django 3.2.7 on 2021-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20211001_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='atelier',
            field=models.ManyToManyField(through='shop.LigneAtelierCommande', to='shop.Atelier'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(through='shop.LigneProduitCommande', to='shop.Produit'),
        ),
    ]
