# Generated by Django 3.2.7 on 2021-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20211001_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='nomFichier',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='nomFichier',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
