# Generated by Django 3.2.7 on 2021-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20211005_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('Envoyé', 'Envoyé'), ('En attente', 'En attente'), ('Annulé', 'Annulé')], default='', max_length=10),
        ),
    ]
