# Generated by Django 3.2.7 on 2021-10-08 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0021_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='favorisAtelier',
            field=models.ManyToManyField(blank=True, related_name='favorisAtelier', to=settings.AUTH_USER_MODEL),
        ),
    ]
