# Generated by Django 3.2.7 on 2021-10-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210929_0908'),
        ('shop', '0022_commande_favorisatelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client'),
        ),
    ]
