# Generated by Django 3.2.8 on 2021-10-11 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0023_alter_commande_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='favorisAtelier',
        ),
        migrations.AddField(
            model_name='atelier',
            name='favorisAtelier',
            field=models.ManyToManyField(blank=True, related_name='favorisAtelier', to=settings.AUTH_USER_MODEL),
        ),
    ]
