# Generated by Django 3.2.7 on 2021-10-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_prix_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='comDatePaiement',
            new_name='comDate',
        ),
    ]
