# Generated by Django 3.2.7 on 2021-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rename_comdatepaiement_commande_comdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='prix',
            field=models.FloatField(),
        ),
    ]
