# Generated by Django 3.2.8 on 2021-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_produit_typeprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='typeProd',
            field=models.CharField(blank=True, choices=[('Cosmétique', 'Cosmétique'), ('Produit intérieur', 'Produit intérieur'), ('Vêtement', 'Vêtement')], max_length=50, null=True),
        ),
    ]
