# Generated by Django 3.2.8 on 2021-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_produit_typeprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='typeProd',
            field=models.CharField(blank=True, choices=[('Cosmetique', 'Cosmetique'), ('Produit interieur', 'Produit interieur'), ('Vetement', 'Vetement')], max_length=50, null=True),
        ),
    ]
