# Generated by Django 3.2.7 on 2021-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_produit_typeprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='comPoidsFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
