# Generated by Django 3.2.8 on 2021-10-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_commande_comtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='comTotal',
            field=models.FloatField(),
        ),
    ]
