# Generated by Django 3.2.8 on 2021-10-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20211011_1151'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panieritem',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.atelier'),
        ),
    ]
