# Generated by Django 3.2.7 on 2021-10-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20211011_1151'),
        ('cart', '0002_panieritem_atelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieritem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produit'),
        ),
    ]
