# Generated by Django 3.2.8 on 2021-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_panieritem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
